const fs = require('fs');

const dataset = [
    { prompt: "New Product Launch:", completion: "5 Tips for a Successful Launch" },
    { prompt: "Join Our Loyalty Program:", completion: "Get Exclusive Rewards and Discounts!" },
    { prompt: "Save on Your Next Purchase:", completion: "Shop Our Sale and Get Up to 50% Off!" },
    { prompt: "Discover the Latest Fashion Trends:", completion: "Shop Our New Collection Now" },
    { prompt: "Get More Done in Less Time:", completion: "Streamline Your Workflow with Our Productivity Tools" },
    { prompt: "The Perfect Gift for Any Occasion:", completion: "Surprise Your Loved Ones with Our Gift Cards" },
    { prompt: "Upgrade Your Home Theater System:", completion: "Experience the Ultimate Viewing Experience with Our Home Theater Systems" },
    { prompt: "Stay Connected on the Go:", completion: "Get Our Mobile App and Never Miss a Thing" },
    { prompt: "Find Your Dream Job:", completion: "Join Our Network of Top Employers and Land Your Next Job" },
    { prompt: "Improve Your Health and Fitness:", completion: "Get Fit and Feel Great with Our Exercise Programs" },
    { prompt: "Take Your Business to the Next Level:", completion: "Unlock Your Potential with Our Business Solutions" },
    { prompt: "Get More Out of Your Shopping Experience:", completion: "Sign Up for Our Rewards Program and Get Exclusive Benefits" },
    { prompt: "Simplify Your Finances:", completion: "Get Our Personal Finance App and Manage Your Money with Ease" },
    { prompt: "Upgrade Your Gaming Setup:", completion: "Get the Latest Gaming Gear and Dominate the Competition" },
    { prompt: "Transform Your Home into a Smart Home:", completion: "Control Your Home with Our Smart Home Solutions" },
    { prompt: "Find Your Perfect Match:", completion: "Join Our Dating Site and Meet Your Soulmate" },
    { prompt: "Get Your Dream Car:", completion: "Get Approved for a Car Loan Today" },
    { prompt: "Experience the World's Best Cuisine:", completion: "Try Our Michelin-Starred Restaurants Today" },
    { prompt: "Get the Perfect Smile:", completion: "Transform Your Smile with Our Cosmetic Dentistry Services" },
    { prompt: "Stay Safe and Secure:", completion: "Protect Your Home and Family with Our Security Solutions" },
    { prompt: "The Ultimate Travel Experience:", completion: "Explore the World with Our Luxury Travel Packages" },
    { prompt: "Get More from Your Music:", completion: "Listen to Your Favorite Songs with Our Premium Music Streaming Service" },
    { prompt: "Make Your Home Energy Efficient:", completion: "Reduce Your Energy Bills with Our Home Energy Solutions" },
    { prompt: "Transform Your Backyard into an Oasis:", completion: "Create Your Dream Outdoor Space with Our Landscaping Services" },
    { prompt: "Get Your Dream Job Overseas:", completion: "Find Your Next International Job with Our Global Recruitment Services" },
    { prompt: "Get the Perfect Look for Your Wedding Day:", completion: "Find Your Dream Wedding Dress with Our Bridal Collection" },
    { prompt: "Stay Healthy and Active at Any Age:", completion: "Join Our Fitness Club and Improve Your Health and Fitness" },
    { prompt: "The Ultimate Gaming Experience:", completion: "Experience the Future of Gaming with Our VR Headset" },
    { prompt: "Find Your Dream Home:", completion: "Discover Your Perfect Home with Our Real Estate Services" },
    { prompt: "Upgrade Your Home Security:", completion: "Protect Your Home with Our Advanced Security Systems" },
{ prompt: "Get Ready for Summer:", completion: "Shop Our Collection of Swimwear and Beachwear" },
{ prompt: "Find Your Perfect Yoga Practice:", completion: "Join Our Yoga Studio and Explore Different Styles" },
{ prompt: "Get the Best Deals on Electronics:", completion: "Shop Our Electronics Sale for Huge Savings" },
{ prompt: "Stay Stylish and Comfortable:", completion: "Find Your Perfect Pair of Shoes with Our Footwear Collection" },
{ prompt: "Transform Your Look with Hair Extensions:", completion: "Get Fuller, Longer Hair with Our Hair Extension Services" },
{ prompt: "Find Your Perfect Scent:", completion: "Shop Our Fragrance Collection for Your Signature Scent" },
{ prompt: "Experience the Best of the Outdoors:", completion: "Discover Our Camping and Hiking Gear Collection" },
{ prompt: "Get Your Dream Home Theater System:", completion: "Create Your Ultimate Home Cinema with Our Home Theater Packages" },
{ prompt: "Stay on Top of Your Finances:", completion: "Get Our Financial Planning Services and Reach Your Goals" },
{ prompt: "Upgrade Your Wardrobe for Less:", completion: "Shop Our Clearance Sale for Huge Discounts on Fashion" },
{ prompt: "Get the Perfect Wedding Venue:", completion: "Plan Your Dream Wedding at Our Stunning Venues" },
{ prompt: "Stay Fit and Healthy with Personal Training:", completion: "Get One-on-One Personal Training with Our Certified Trainers" },
{ prompt: "Find Your Perfect Vacation Rental:", completion: "Book Your Dream Vacation Home with Our Rental Services" },
{ prompt: "Get the Best Deals on Home Goods:", completion: "Shop Our Home Goods Sale for Huge Savings" },
{ prompt: "Transform Your Space with Interior Design:", completion: "Create Your Dream Home with Our Interior Design Services" },
{ prompt: "Get Your Dream Job in Tech:", completion: "Join Our Network of Top Tech Companies and Land Your Next Job" },
{ prompt: "Stay Protected on the Road:", completion: "Get Our Car Insurance and Drive with Confidence" },
{ prompt: "Find Your Perfect Pet:", completion: "Adopt a Loving Pet from Our Animal Shelter" },
{ prompt: "Experience the Best of Local Cuisine:", completion: "Discover Our Collection of Local Restaurants and Food Tours" },
{ prompt: "Get the Perfect Look for Any Occasion:", completion: "Find Your Dream Outfit with Our Fashion Collection" },
{ prompt: "Stay Connected with Your Loved Ones:", completion: "Stay in Touch Anywhere with Our Communication Solutions" },
{ prompt: "Protect Your Skin from the Sun:", completion: "Stay Safe in the Sun with Our Sunscreen Products" },
{ prompt: "Experience the Ultimate Gaming Performance:", completion: "Get Our High-Performance Gaming PCs and Conquer Any Game" },
{ prompt: "Get the Perfect Sound for Your Ears:", completion: "Experience Crystal-Clear Audio with Our Premium Headphones" },
{ prompt: "Upgrade Your Photography Game:", completion: "Capture Your Memories with Our High-Quality Cameras" },
{ prompt: "Get Your Dream Job in Tech:", completion: "Join Our Network of Top Tech Companies and Land Your Next Job" },
{ prompt: "Find Your Perfect Vacation Destination:", completion: "Explore the World with Our Travel Guides and Book Your Next Adventure" },
{ prompt: "Get the Perfect Hairstyle:", completion: "Transform Your Look with Our Professional Hair Styling Services" },
{ prompt: "Stay Cool in the Summer Heat:", completion: "Beat the Heat with Our Air Conditioning Systems" },
{ prompt: "Experience the Ultimate Driving Experience:", completion: "Drive in Style with Our Luxury Cars" },
{ prompt: "Stay Organized and Productive:", completion: "Manage Your Tasks with Our Productivity Tools" },
{ prompt: "Upgrade Your Home Office:", completion: "Work Smarter with Our Home Office Solutions" },
{ prompt: "Transform Your Home into a Smart Home:", completion: "Control Your Home with Our Smart Home Solutions" },
{ prompt: "Get More from Your TV Viewing Experience:", completion: "Watch Your Favorite Shows with Our High-Definition TVs" },
{ prompt: "Find Your Perfect Pet:", completion: "Adopt Your New Best Friend with Our Pet Adoption Services" },
{ prompt: "Get the Perfect Party Supplies:", completion: "Throw the Ultimate Party with Our Party Supplies" },
{ prompt: "Stay Stylish and Comfortable:", completion: "Find Your Perfect Fit with Our Clothing Collection" },
{ prompt: "Transform Your Backyard into a Playground:", completion: "Create Your Dream Play Area with Our Playground Equipment" },
{ prompt: "Get Your Dream Job in Marketing:", completion: "Join Our Network of Top Marketing Companies and Land Your Next Job" },
{ prompt: "Experience the Ultimate Home Entertainment:", completion: "Get Our Home Theater System and Enjoy the Ultimate Viewing Experience" },
{ prompt: "Get the Perfect Gift for Your Loved Ones:", completion: "Surprise Your Friends and Family with Our Gift Ideas" },
{ prompt: "Stay Protected from Cyber Threats:", completion: "Secure Your Digital Life with Our Cybersecurity Solutions" },
{ prompt: "Upgrade Your Outdoor Living Space:", completion: "Create Your Dream Outdoor Space with Our Patio Furniture Collection" },
{ prompt: "Get More from Your Workouts:", completion: "Get Fit and Stay Healthy with Our Fitness Programs" },
{ prompt: "Experience the Best Spa Treatments:", completion: "Relax and Rejuvenate with Our Spa Services" },
{ prompt: "Find Your Perfect Wedding Venue:", completion: "Say 'I Do' in Your Dream Wedding Venue with Our Wedding Services" },
{ prompt: "Get Your Dream Job in Finance:", completion: "Join Our Network of Top Finance Companies and Land Your Next Job" },
{ prompt: "The Best Coffee Around:", completion: "Taste Our Premium Blend Today!" },
{ prompt: "Stay Warm and Cozy this Winter:", completion: "Shop Our Collection of Knitwear and Sweaters" },
{ prompt: "Get Ready for Summer:", completion: "Find Your Perfect Swimsuit with Our Swimwear Collection" },
{ prompt: "Experience the Great Outdoors:", completion: "Explore Nature with Our Camping and Hiking Gear" },
{ prompt: "Get the Perfect Tan:", completion: "Find Your Ideal Tanning Solution with Our Products" },
{ prompt: "Transform Your Living Space:", completion: "Redesign Your Home with Our Interior Design Services" },
{ prompt: "Find Your Ideal Workout Partner:", completion: "Join Our Fitness Community and Meet Like-Minded People" },
{ prompt: "Discover the Best Local Cuisine:", completion: "Explore Your City's Food Scene with Our Food Tours" },
{ prompt: "Get Your Dream Body:", completion: "Transform Your Physique with Our Personal Training Services" },
{ prompt: "Upgrade Your Computer Setup:", completion: "Get the Latest Technology with Our Computer Accessories" },
{ prompt: "Find Your Perfect Vacation Spot:", completion: "Plan Your Next Getaway with Our Travel Services" },
{ prompt: "Get Your Dream Wedding Venue:", completion: "Book Your Perfect Wedding Venue with Our Services" },
{ prompt: "Improve Your Mental Health:", completion: "Find Peace of Mind with Our Therapy Services" },
{ prompt: "Discover Your Perfect Fragrance:", completion: "Find Your Signature Scent with Our Perfume Collection" },
{ prompt: "Upgrade Your Style Game:", completion: "Get the Latest Fashion Trends with Our Clothing Collection" },
{ prompt: "Find Your Ideal Pet:", completion: "Adopt Your New Best Friend from Our Animal Shelter" },
{ prompt: "Get Your Dream Home Theater System:", completion: "Experience the Ultimate Viewing Experience with Our Audio and Video Systems" },
{ prompt: "Stay Healthy and Hydrated:", completion: "Get Your Daily Dose of Vitamins with Our Health Supplements" },
{ prompt: "Transform Your Skin:", completion: "Get Flawless Skin with Our Skincare Products" },
{ prompt: "Find Your Ideal Career Path:", completion: "Discover Your Passion with Our Career Coaching Services" },
{ prompt: "Get Your Dream Bedroom:", completion: "Create Your Perfect Sleeping Space with Our Bedding Collection" },
{ prompt: "Stay Active and Fit at Home:", completion: "Get Your Workout Done Anytime with Our Home Fitness Equipment" },
{ prompt: "Upgrade Your Outdoor Space:", completion: "Create Your Perfect Backyard Oasis with Our Patio Furniture" },
{ prompt: "Find Your Ideal Business Partner:", completion: "Grow Your Business with Our Business Networking Services" },
{ prompt: "Get Your Dream Boat:", completion: "Explore the Open Seas with Our Boat Rental Services" },
{ prompt: "Experience the Ultimate Relaxation:", completion: "Unwind and De-Stress with Our Spa Services" },
{ prompt: "Get Your Dream Wedding Cake:", completion: "Make Your Big Day Special with Our Wedding Cakes" },
{ prompt: "Stay Protected from the Sun:", completion: "Get the Best Sun Protection with Our Sunscreen Products" },
{ prompt: "Transform Your Hair:", completion: "Get the Perfect Hairstyle with Our Hair Salon Services" },
{ prompt: "Find Your Ideal Volunteer Opportunity:", completion: "Make a Difference in Your Community with Our Volunteer"}

]  

// Convert dataset to CSV format
const csv = dataset.map(row => Object.values(row).join(',')).join('\n');

// Write CSV to file
fs.writeFileSync('dataset2.csv', csv);